// <auto-generated />
using System;
using FinanceApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceApp.Domain.Entities.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TransacaoId")
                        .HasColumnType("int");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Anexos", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.ApelidoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Apelido", "UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("ApelidosCategorias", "FinanceApp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apelido = "comida",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Apelido = "almoco",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Apelido = "janta",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Apelido = "lanche",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Apelido = "ifood",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Apelido = "restaurante",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Apelido = "cafe",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 8,
                            Apelido = "padaria",
                            CategoriaId = 1
                        },
                        new
                        {
                            Id = 9,
                            Apelido = "uber",
                            CategoriaId = 2
                        },
                        new
                        {
                            Id = 10,
                            Apelido = "onibus",
                            CategoriaId = 2
                        },
                        new
                        {
                            Id = 11,
                            Apelido = "99",
                            CategoriaId = 2
                        },
                        new
                        {
                            Id = 12,
                            Apelido = "taxi",
                            CategoriaId = 2
                        },
                        new
                        {
                            Id = 13,
                            Apelido = "passagem",
                            CategoriaId = 2
                        },
                        new
                        {
                            Id = 14,
                            Apelido = "metro",
                            CategoriaId = 2
                        },
                        new
                        {
                            Id = 15,
                            Apelido = "aluguel",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 16,
                            Apelido = "condominio",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 17,
                            Apelido = "luz",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 18,
                            Apelido = "agua",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 19,
                            Apelido = "internet",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 20,
                            Apelido = "energia",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 21,
                            Apelido = "gas",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 22,
                            Apelido = "iptu",
                            CategoriaId = 3
                        },
                        new
                        {
                            Id = 23,
                            Apelido = "remedio",
                            CategoriaId = 4
                        },
                        new
                        {
                            Id = 24,
                            Apelido = "farmacia",
                            CategoriaId = 4
                        },
                        new
                        {
                            Id = 25,
                            Apelido = "medico",
                            CategoriaId = 4
                        },
                        new
                        {
                            Id = 26,
                            Apelido = "consulta",
                            CategoriaId = 4
                        },
                        new
                        {
                            Id = 27,
                            Apelido = "dentista",
                            CategoriaId = 4
                        },
                        new
                        {
                            Id = 28,
                            Apelido = "exame",
                            CategoriaId = 4
                        },
                        new
                        {
                            Id = 29,
                            Apelido = "curso",
                            CategoriaId = 5
                        },
                        new
                        {
                            Id = 30,
                            Apelido = "livro",
                            CategoriaId = 5
                        },
                        new
                        {
                            Id = 31,
                            Apelido = "faculdade",
                            CategoriaId = 5
                        },
                        new
                        {
                            Id = 32,
                            Apelido = "escola",
                            CategoriaId = 5
                        },
                        new
                        {
                            Id = 33,
                            Apelido = "cinema",
                            CategoriaId = 6
                        },
                        new
                        {
                            Id = 34,
                            Apelido = "netflix",
                            CategoriaId = 6
                        },
                        new
                        {
                            Id = 35,
                            Apelido = "spotify",
                            CategoriaId = 6
                        },
                        new
                        {
                            Id = 36,
                            Apelido = "jogo",
                            CategoriaId = 6
                        },
                        new
                        {
                            Id = 37,
                            Apelido = "bar",
                            CategoriaId = 6
                        },
                        new
                        {
                            Id = 38,
                            Apelido = "festa",
                            CategoriaId = 6
                        },
                        new
                        {
                            Id = 39,
                            Apelido = "viagem",
                            CategoriaId = 6
                        },
                        new
                        {
                            Id = 40,
                            Apelido = "roupa",
                            CategoriaId = 7
                        },
                        new
                        {
                            Id = 41,
                            Apelido = "calcado",
                            CategoriaId = 7
                        },
                        new
                        {
                            Id = 42,
                            Apelido = "tenis",
                            CategoriaId = 7
                        },
                        new
                        {
                            Id = 43,
                            Apelido = "shein",
                            CategoriaId = 7
                        },
                        new
                        {
                            Id = 44,
                            Apelido = "gasolina",
                            CategoriaId = 8
                        },
                        new
                        {
                            Id = 45,
                            Apelido = "etanol",
                            CategoriaId = 8
                        },
                        new
                        {
                            Id = 46,
                            Apelido = "combustivel",
                            CategoriaId = 8
                        },
                        new
                        {
                            Id = 47,
                            Apelido = "posto",
                            CategoriaId = 8
                        },
                        new
                        {
                            Id = 48,
                            Apelido = "diesel",
                            CategoriaId = 8
                        },
                        new
                        {
                            Id = 49,
                            Apelido = "assinatura",
                            CategoriaId = 9
                        },
                        new
                        {
                            Id = 50,
                            Apelido = "mensalidade",
                            CategoriaId = 9
                        },
                        new
                        {
                            Id = 51,
                            Apelido = "academia",
                            CategoriaId = 9
                        },
                        new
                        {
                            Id = 52,
                            Apelido = "streaming",
                            CategoriaId = 9
                        },
                        new
                        {
                            Id = 53,
                            Apelido = "mercado",
                            CategoriaId = 10
                        },
                        new
                        {
                            Id = 54,
                            Apelido = "supermercado",
                            CategoriaId = 10
                        },
                        new
                        {
                            Id = 55,
                            Apelido = "feira",
                            CategoriaId = 10
                        },
                        new
                        {
                            Id = 56,
                            Apelido = "hortifruti",
                            CategoriaId = 10
                        },
                        new
                        {
                            Id = 57,
                            Apelido = "acougue",
                            CategoriaId = 10
                        },
                        new
                        {
                            Id = 58,
                            Apelido = "racao",
                            CategoriaId = 11
                        },
                        new
                        {
                            Id = 59,
                            Apelido = "veterinario",
                            CategoriaId = 11
                        },
                        new
                        {
                            Id = 60,
                            Apelido = "petshop",
                            CategoriaId = 11
                        },
                        new
                        {
                            Id = 61,
                            Apelido = "cabelo",
                            CategoriaId = 12
                        },
                        new
                        {
                            Id = 62,
                            Apelido = "unha",
                            CategoriaId = 12
                        },
                        new
                        {
                            Id = 63,
                            Apelido = "salao",
                            CategoriaId = 12
                        },
                        new
                        {
                            Id = 64,
                            Apelido = "barbearia",
                            CategoriaId = 12
                        },
                        new
                        {
                            Id = 65,
                            Apelido = "fatura",
                            CategoriaId = 13
                        },
                        new
                        {
                            Id = 66,
                            Apelido = "cartao",
                            CategoriaId = 13
                        },
                        new
                        {
                            Id = 67,
                            Apelido = "acao",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 68,
                            Apelido = "acoes",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 69,
                            Apelido = "fii",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 70,
                            Apelido = "cdb",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 71,
                            Apelido = "tesouro",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 72,
                            Apelido = "cripto",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 73,
                            Apelido = "bitcoin",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 74,
                            Apelido = "poupanca",
                            CategoriaId = 14
                        },
                        new
                        {
                            Id = 75,
                            Apelido = "presente",
                            CategoriaId = 15
                        },
                        new
                        {
                            Id = 76,
                            Apelido = "doacao",
                            CategoriaId = 15
                        },
                        new
                        {
                            Id = 77,
                            Apelido = "imposto",
                            CategoriaId = 15
                        },
                        new
                        {
                            Id = 78,
                            Apelido = "multa",
                            CategoriaId = 15
                        });
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bandeira")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ContaId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("int");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("LimiteDisponivel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LimiteTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UltimosDigitos")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CartoesCredito", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("Padrao")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Categorias", "FinanceApp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cor = "#FF6B6B",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1289),
                            Icone = "utensils",
                            Nome = "Alimentacao",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Cor = "#4ECDC4",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1296),
                            Icone = "car",
                            Nome = "Transporte",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Cor = "#45B7D1",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1299),
                            Icone = "home",
                            Nome = "Moradia",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Cor = "#96CEB4",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1301),
                            Icone = "heart-pulse",
                            Nome = "Saude",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Cor = "#FFEAA7",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1302),
                            Icone = "graduation-cap",
                            Nome = "Educacao",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Cor = "#DDA0DD",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1304),
                            Icone = "gamepad-2",
                            Nome = "Lazer",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Cor = "#F0E68C",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1306),
                            Icone = "shirt",
                            Nome = "Vestuario",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Cor = "#FFB347",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1307),
                            Icone = "fuel",
                            Nome = "Combustivel",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Cor = "#87CEEB",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1311),
                            Icone = "repeat",
                            Nome = "Assinaturas",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Cor = "#98D8C8",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1313),
                            Icone = "shopping-cart",
                            Nome = "Mercado",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Cor = "#C9B1FF",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1315),
                            Icone = "paw-print",
                            Nome = "Pets",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Cor = "#FFB6C1",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1316),
                            Icone = "sparkles",
                            Nome = "Beleza",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Cor = "#FF4757",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1318),
                            Icone = "credit-card",
                            Nome = "Cartao de Credito",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Cor = "#E17055",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1320),
                            Icone = "trending-down",
                            Nome = "Investimentos",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Cor = "#B0BEC5",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1330),
                            Icone = "ellipsis",
                            Nome = "Outros",
                            Padrao = true,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Cor = "#27AE60",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1333),
                            Icone = "banknote",
                            Nome = "Salario",
                            Padrao = true,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Cor = "#2ECC71",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1334),
                            Icone = "laptop",
                            Nome = "Freelance",
                            Padrao = true,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            Cor = "#1ABC9C",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1336),
                            Icone = "trending-up",
                            Nome = "Rendimentos",
                            Padrao = true,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            Cor = "#3498DB",
                            CriadoEm = new DateTime(2026, 6, 17, 12, 52, 49, 402, DateTimeKind.Utc).AddTicks(1338),
                            Icone = "plus-circle",
                            Nome = "Outros Ganhos",
                            Padrao = true,
                            Tipo = "RECEITA"
                        });
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.CodigoVerificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CodigosVerificacao", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.ConfiguracaoUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("AlertasFatura")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertasOrcamento")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaInicioMes")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("ModoEscuro")
                        .HasColumnType("bit");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("NotificacoesPush")
                        .HasColumnType("bit");

                    b.Property<bool>("WhatsAppAtivado")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId");

                    b.ToTable("ConfiguracoesUsuario", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Banco")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contas", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.FaturaCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartaoCreditoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataFechamento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CartaoCreditoId", "MesReferencia", "AnoReferencia")
                        .IsUnique();

                    b.ToTable("FaturasCartao", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FormasPagamento", "FinanceApp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icone = "banknote",
                            Nome = "Dinheiro"
                        },
                        new
                        {
                            Id = 2,
                            Icone = "credit-card",
                            Nome = "Cartao de Credito"
                        },
                        new
                        {
                            Id = 3,
                            Icone = "credit-card",
                            Nome = "Cartao de Debito"
                        },
                        new
                        {
                            Id = 4,
                            Icone = "qr-code",
                            Nome = "PIX"
                        },
                        new
                        {
                            Id = 5,
                            Icone = "file-text",
                            Nome = "Boleto"
                        },
                        new
                        {
                            Id = 6,
                            Icone = "arrow-right-left",
                            Nome = "Transferencia"
                        });
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.LancamentoMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaEconomiaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MetaEconomiaId");

                    b.ToTable("LancamentosMeta", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EntidadeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Navegador")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoEntidade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNovo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "CriadoEm")
                        .IsDescending(false, true);

                    b.ToTable("LogsAuditoria", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.MensagemWhatsApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaIdentificada")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MensagemOriginal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ProcessadoComSucesso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorIdentificado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroTelefone");

                    b.HasIndex("TransacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensagensWhatsApp", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.MetaEconomia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Concluida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataLimite")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MetasEconomia", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntidadeRelacionadaId")
                        .HasColumnType("int");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Lida", "CriadoEm")
                        .IsDescending(false, false, true);

                    b.ToTable("Notificacoes", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("PercentualAlerta")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorLimite")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId", "CategoriaId", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("Orcamentos", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Parcelamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CartaoCreditoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataPrimeiraParcela")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ParcelasPagas")
                        .HasColumnType("int");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Parcelamentos", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.RegraRecorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("DiaMes")
                        .HasColumnType("int");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("UltimaGeracaoEm")
                        .HasColumnType("date");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegrasRecorrencia", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.TokenAtualizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubstituidoPor")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensAtualizacao", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CartaoCreditoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataTransacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("FaturaCartaoId")
                        .HasColumnType("int");

                    b.Property<int?>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ParcelamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("bit");

                    b.Property<int?>("RegraRecorrenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("TotalParcelas")
                        .HasColumnType("int");

                    b.Property<int?>("TransferenciaContaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("FaturaCartaoId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("ParcelamentoId");

                    b.HasIndex("RegraRecorrenciaId");

                    b.HasIndex("TransferenciaContaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "CategoriaId");

                    b.HasIndex("UsuarioId", "ContaId");

                    b.HasIndex("UsuarioId", "DataTransacao")
                        .IsDescending(false, true);

                    b.ToTable("Transacoes", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.TransferenciaConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("ContaOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataTransferencia")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TransferenciasContas", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneWhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TelefoneWhatsApp")
                        .IsUnique()
                        .HasFilter("[TelefoneWhatsApp] IS NOT NULL");

                    b.ToTable("Usuarios", "FinanceApp");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "FinanceApp");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "FinanceApp");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioClaims", "FinanceApp");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioLogins", "FinanceApp");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", "FinanceApp");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuarioTokens", "FinanceApp");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Anexo", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Transacao", "Transacao")
                        .WithMany("Anexos")
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Transacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.ApelidoCategoria", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Apelidos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.CartaoCredito", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Conta", "Conta")
                        .WithMany("CartoesCredito")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("CartoesCredito")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.CodigoVerificacao", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.ConfiguracaoUsuario", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Configuracoes")
                        .HasForeignKey("FinanceApp.Domain.Entities.ConfiguracaoUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Conta", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.FaturaCartao", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Faturas")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.LancamentoMeta", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.MetaEconomia", "MetaEconomia")
                        .WithMany("Lancamentos")
                        .HasForeignKey("MetaEconomiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaEconomia");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.MensagemWhatsApp", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Transacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.MetaEconomia", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MetasEconomia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Orcamento", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Orcamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Parcelamento", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Parcelamentos")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.RegraRecorrencia", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RegrasRecorrencia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.TokenAtualizacao", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TokensAtualizacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.CartaoCredito", "CartaoCredito")
                        .WithMany("Transacoes")
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Conta", "Conta")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.FaturaCartao", "FaturaCartao")
                        .WithMany("Transacoes")
                        .HasForeignKey("FaturaCartaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany("Transacoes")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.Parcelamento", "Parcelamento")
                        .WithMany("Transacoes")
                        .HasForeignKey("ParcelamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.RegraRecorrencia", "RegraRecorrencia")
                        .WithMany("Transacoes")
                        .HasForeignKey("RegraRecorrenciaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.TransferenciaConta", "TransferenciaConta")
                        .WithMany("Transacoes")
                        .HasForeignKey("TransferenciaContaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoCredito");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("FaturaCartao");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Parcelamento");

                    b.Navigation("RegraRecorrencia");

                    b.Navigation("TransferenciaConta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.TransferenciaConta", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Conta", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Conta", "ContaOrigem")
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FinanceApp.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.CartaoCredito", b =>
                {
                    b.Navigation("Faturas");

                    b.Navigation("Parcelamentos");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Apelidos");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Conta", b =>
                {
                    b.Navigation("CartoesCredito");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.FaturaCartao", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.FormaPagamento", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.MetaEconomia", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Parcelamento", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.RegraRecorrencia", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Transacao", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.TransferenciaConta", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinanceApp.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("CartoesCredito");

                    b.Navigation("Configuracoes");

                    b.Navigation("Contas");

                    b.Navigation("MetasEconomia");

                    b.Navigation("Notificacoes");

                    b.Navigation("Orcamentos");

                    b.Navigation("RegrasRecorrencia");

                    b.Navigation("TokensAtualizacao");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
